yarnPath: .yarn/releases/yarn-2.4.1.cjs
nodeLinker: "node-modules"

initFields:
  homepage: "https://yarnpkg.com"
  repository:
    "type": "git"
    "url": "https://github.com/airtonix/mailspring-plugins"
